# Generated by Django 2.2.17 on 2021-05-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_category_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
